### ISSUE TITLE
How do you run and test this repo locally?

### ISSUE THREAD

**Issue by schellenbergk** [pixijs/pixi-particles-editor#23]
What the title says.

**Comment by andrewstart** [comment]
It's been a very long time since I have done so, so I don't remember specifics to give you, but you do need Bower (not an NPM dependency, it appears) and Grunt (is an npm dependency), but it is also probable that you need to use a much older version of Node for the tools to run. The default command of `grunt` should either build the project or give you a list of registered commands. I don't see any sign of any sort of serve command, so I would guess you need a separate basic server for local testing, like `http-server`.

**Comment by schellenbergk** [comment]
I guess its time for a rewrite :)... My initial issue was with EmitterConfigV1, but I found a workaround for it.   Thanks for your response :).
